services:
  app:
    build: .
    image: ia-current:latest
    environment:
      DISPLAY: :99
      TESSERACT_CMD: /usr/bin/tesseract
    expose:
      - "6080"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
